### PR TITLE
Remove binaries

### PR DESCRIPTION
**Pull request by joncham**
Remove old dylibs that supported System.Drawing.
Avoid copying boehm variants of runtime since we don't need it.

### CODE REVIEW

**Review by mderoy — APPROVED** [review]

**Comment by joshpeterson** [comment]
My only concern is the `monodistribution/lib/libMonoPosixHelper.dylib` file. This was the one that we were having trouble getting the 32-bit and 64-bit slice packaged correctly. We noticed that because the IL2CPP integration tests do use it. So is it safe to remove?

**Comment by joncham** [comment]
@joshpeterson I hope the one I reference is not used as I think it's old and only 32-bit?
Maybe that caused part of our issue?

Also, I did a test build of these changes. ABV and QV are green.

**Comment by joshpeterson** [comment]
@joncham I think the problem only showed up in the IL2CPP integration tests, so ABV and QA won't catch it. Can you run the IL2CPP tests on macOS to be sure?

**Review by mrvoorhe — APPROVED** [review]

**Review by joshpeterson — APPROVED** [review]

**Comment by joshpeterson** [comment]
The IL2CPP integration tests are passing with these changes.

**Pull request merged**
